### ISSUE TITLE
RFC: remove the /apps/APP/vms dir and re-parent each VM dir directly under /apps/APP? 

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#126]
It seems the `/apps/APP/vms` dir is kinda pointless other than to make it clear that the subdirs are in fact VMs... I dunno. Comment?

**Comment by ajblum** [comment]
yea, id agree, in fact i forget that extra dir sometimes when im typing fast.

Are there other objects that can be manipulated other than VMs ?  I'm thinking about the new networking editing.  That might be a reason to keep the vms/ dir...to separate from a network/.  There might also be a use to see the logs for a given app as well so might have:

/apps/APP/vms
/apps/APP/network
/apps/APP/log

Similar to how the webui breaks out the different tabs for an application.

--
Andrew

**Comment by ryran** [comment]
>  That might be a reason to keep the vms/ dir...to separate from a network/. There might also be a use to see the logs for a given app as well ...

Yeah I agree. I'll just leave it alone. :)
