### ISSUE TITLE
[RFE] Notifications for app timeout, app start, app shutdown, etc

### ISSUE THREAD

**Issue by THEdoubleh** [ryran/ravshello#16]
RFE for gnome notifications for app timeout, specifically for admins

**Comment by ryran** [comment]
Yesssss. I think what this would need to look like:

Ravshello kicks off a subprocess which would use the notifications API to listen for relevant events

This could be accomplished by implementing threading (ahhhhhhhh).

More likely though, ravshello would ship with (and blindly launch) a separate util that would listen for things and trigger event notifications with gnome's `notify-send` command. Yes. Yes. That's what I'll do.

**Comment by ryran** [comment]
Boom boom boom.

Put something together over the weekend. For now, this functionality will live in a separate python app. Added to `rav-notify-util` branch.

**Comment by ryran** [comment]
This work was merged into master branch. Still separate from ravshello itself for now, but uses the same [optional] yaml config file as ravshello. Closing for now. Will look into it some more once Ravello reveals the new user ACL stuff.
