### ISSUE TITLE
update login() to support new Identity Domains

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#173]
The python sdk from Ravello already supports this:

> 
> login(username=None, password=None, identity_domain=None)
> 
>     Login to the API.
> 
>     This method performs a login to the API, and store the resulting authentication cookie in memory.
> 
>     It is not mandatory to call this method. If this method is not called, the client will automatically login when required.
> 
>     When the organization of the user has an identity domain, the user must specify it or include it in the username: <identity_domain>/<username>. When the organization doesnt have an identity domain use only the username.

Right now, it's still possible to authenticate with username and passwd only, but Identity Domain will soon be required.

Probably want to accept Identity Domain in all the same ways as username/password (ie argument, config, prompt).

**Comment by ryran** [comment]
Hey @ajblum 

> Right now, it's still possible to authenticate with username and passwd only, but Identity Domain will soon be required.

I read the email you forwarded too, but to me it suggested that you'd only need this if you had the same email address in multiple different accounts ... something that they have perhaps allowed only recently? Am I misunderstanding?

Furthermore, it looks like you can just prefix your username with `<identity_domain>/`. From sdk that ravshello already uses:

```
╔═[rsaw@xala 23:07 ~] {0} $ ravshello -QD0a <<<'help(r.__init__)'
Help on method __init__ in module modules.ravello_sdk:

__init__(self, username=None, password=None, url=None, timeout=None, retries=None, proxy_url=None, eph_token=None, identity_domain=None) method of modules.ravello_sdk.RavelloClient instance
    Create a new client.
    
    The *username* and *password* parameters specify the credentials to use
    when connecting to the API. When the organization of the user has an identity domain,
    the user must specify it or include it in the username: <identity_domain>/<username>.
    When the organization doesnt have an identity domain use only the username.
    The *timeout* and *retries* parameters
    specify the default network system call time timeout and maximum number
    of retries respectively.
    *proxy_url* should be used when an HTTP proxy is in place.
    *eph_token* is ephemeral access token to be used instead of username/password.

╔═[rsaw@xala 23:07 ~] {0} $ 
```
It would seem to me *that* would be far less clunky than adding another option. What do you think?

**Comment by ryran** [comment]
On a call with Ravello just now, they said that they're planning to make their API require identity domain pretty soon, so that's fun.

**Comment by ryran** [comment]
That said, I'm closing this issue since there's nothing we need to do.
