### ISSUE TITLE
simplify command names?

### ISSUE THREAD

**Issue by ryran** [ryran/ravshello#47]
Bear with me here ... but the `stop_app` and `start_app` commands are annoyingly long and similar. What if instead they were `start` and `poweroff`? Same for the vm commands.

What about `create_app`? Maybe just rename it to `create`? And do the same for all the other commands (i.e., drop the `_suffix` at the end).

Thoughts?

**Comment by ajblum** [comment]
I'd be ok with those changes.  Will need to update documentation accordingly, but its seems reasonable.
--
Andrew
