### ISSUE TITLE
need to set expiry timer for restarts

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#64]
In ravshello/user_interface.py  def ui_command_restart(self): there is no 
```
 self.extend_autostop(minutes=defaultAppExpireTime)
```

The net result is, when a person issues a restart no expiry is set and the application will have a **Never** expiry.  My suggestion is that you set the autostop for restarts in the same way you do for starts.

Thanks !
--
Andrew

**Comment by ryran** [comment]
@ajblum 
HI Andrew!!! Man you should have pinged me directly about this. That's a big deal ... can't believe a bug like this sat there the whole time. I'm on a real tight timeline to prepare some training for a day-long workshop tomorrow but we can definitely get this taken care of this week.
