### ISSUE TITLE
csv billing report appHours is misleading

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#65]
The billing report returned using **/billing export_month_to_csv** returns this information:

```
User,App Name,App Hours,App Charges
ablum,myappname_0,25.0,6.567817565
ablum,myappname_1,24.0,7.2685541745
ablum,myappname_2,24.0,7.2685521571
ablum,myappname_3,36.0,10.902832361
```

`App Hours` listed above is misleading since its really the product of the `number of units consumed by the blueprint` * `total upTime` 

I suggest that we modify ravshello to include another column `Up Time Hours` and to modify `App Hours` to be `Unit Hours`.  

Code suggestion to follow.

**Comment by ajblum** [comment]
[ablum@training3 ravshello]$ diff user_interface.py ~/ravshello/user_interface.py.BACKUP 
830,833d829
<             try:
<                 upTime = app['upTime']
<             except:
<                 upTime = "UNDEFINED"
874,875c870
<                 'unitHours': hours,
<                 'upTime': upTime,
---
>                 'appHours': hours,
885c880
<             "User,App Name,Unit Hours,Up Time Hours,App Charges"
---
>             "User,App Name,App Hours,App Charges"
889,890c884,885
<                 out.append("{},{},{},{},{}".format(
<                     user, app['appName'], app['unitHours'], app['upTime'], app['totalCharges']))
---
>                 out.append("{},{},{},{}".format(
>                     user, app['appName'], app['appHours'], app['totalCharges']))

**Comment by ajblum** [comment]
This change should result in:

```
User,App Name,Unit Hours,Up Time Hours,App Charges
ablum,myappname_0,25.0,5,6.567817565
ablum,myappname_1,24.0,2,7.2685541745
ablum,myappname_2,24.0,2,7.2685521571
ablum,myappname_3,36.0,3,10.902832361
```

**Comment by ryran** [comment]
Hey Andrew! Wife is out of town this weekend so I'm not sure if I'll get to this, but definitely we can make it a priority to get this and the other new-api-changes-thing taken care of over the next week.
